on:
  push:
    branches:
      - main
  workflow_dispatch:

name: push-build&deploy-localRepo

permissions:
  contents: write

env:
  PREFIX: 

jobs:
  build-and-push:
    name: Push to local - Build and deploy site to Github Pages on local repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 16

      - name: Set up Next.js
        run: |
          npm install

      - name: Build site
        run: |
          npm run build
          npm run export
          npm run build:images
          touch out/.nojekyll
    
      - name: Deploy to local repo Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
